"""
app.py — FastAPI application instance for the AI Driving Assistant.

Day 7: Turns the local OpenCV pipeline into a network service that any HTTP
client or WebSocket consumer (Day 9 frontend) can connect to.

Routes
------
GET  /              → Health check + API metadata (JSON)
GET  /health        → Minimal liveness probe (for Docker / load balancers)
GET  /docs          → Swagger UI (auto-generated by FastAPI)
GET  /redoc         → ReDoc UI (alternate API docs)
WS   /ws/stream     → The main event: live annotated frames + metadata JSON

Usage
-----
From the project root, run:

    uvicorn src.api.app:app --host 0.0.0.0 --port 8000 --reload

Or via the convenience script:

    python src/run_server.py

Then open the browser at:
  - http://localhost:8000        (root info + link to docs)
  - http://localhost:8000/docs   (Swagger UI — explore the WebSocket schema)
  - ws://localhost:8000/ws/stream (connect with websocat or the Day 9 frontend)

Architecture decision: one app instance, per-connection pipeline
---------------------------------------------------------------
The pipeline (VideoSource + FrameProcessor with all stages) is constructed
*inside* the WebSocket handler for each client connection, not at app startup.
This means:
  - No shared mutable state between connections — thread-safety is trivially
    guaranteed because each connection has its own VideoSource and stage objects.
  - Multiple simultaneous clients each replay the video independently.
  - Heavy model loading (YOLOv8, MiDaS) happens on first WebSocket connect, not
    at startup — the /health endpoint responds immediately even before any client
    has connected and triggered model downloads.

For a production multi-client broadcast scenario you would instead build the
pipeline once at startup (using the `lifespan` context manager below), share it
across connections via an asyncio queue, and send frames to all subscribers. That
is left for a future day — for Day 9 (single-client dashboard) this design is
simpler and correct.
"""

from __future__ import annotations

from contextlib import asynccontextmanager
from pathlib import Path

from fastapi import FastAPI, WebSocket
from fastapi.middleware.cors import CORSMiddleware

from src.api.websocket_handler import stream_pipeline
from src.utils.logger import get_logger, setup_logging

logger = get_logger(__name__)

_PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent

# ── Lifespan (startup / shutdown) ─────────────────────────────────────────────

@asynccontextmanager
async def lifespan(app: FastAPI):
    """
    FastAPI lifespan context — runs setup before the server accepts requests
    and teardown after the last connection closes.

    Currently used for:
      - Configuring the project logger (same log level as config.yaml).

    NOT used for model pre-loading — see architecture note in the module
    docstring above for why.
    """
    # ── Startup ───────────────────────────────────────────────────────────
    from src.utils.config import load_config
    config_path = _PROJECT_ROOT / "configs" / "config.yaml"
    try:
        config = load_config(str(config_path))
        log_cfg = config.get("logging", {})
        setup_logging(
            level=log_cfg.get("level", "INFO"),
            log_file=log_cfg.get("log_file"),
        )
    except Exception as exc:  # noqa: BLE001
        # Don't crash the server if config is missing — fall back to INFO
        setup_logging(level="INFO")
        logger.warning("Could not load config at startup: %s", exc)

    logger.info("=" * 60)
    logger.info("AI Driving Assistant — Day 7 API Server starting.")
    logger.info("  WebSocket stream : ws://localhost:8000/ws/stream")
    logger.info("  Swagger UI       : http://localhost:8000/docs")
    logger.info("=" * 60)

    yield  # Server runs here

    # ── Shutdown ──────────────────────────────────────────────────────────
    logger.info("Server shutting down. Goodbye.")


# ── App instance ──────────────────────────────────────────────────────────────

app = FastAPI(
    title="AI Driving Assistant API",
    description=(
        "Real-time ADAS pipeline exposed as a WebSocket stream.\n\n"
        "Connect to **`ws://localhost:8000/ws/stream`** to receive a continuous "
        "stream of annotated frames (JPEG/base64) and structured JSON metadata "
        "(detections, lane offset, TTC, risk level, active alert).\n\n"
        "See the `FramePayload` schema below for the exact message structure."
    ),
    version="0.7.0",
    docs_url="/docs",
    redoc_url="/redoc",
    lifespan=lifespan,
)

# ── CORS ──────────────────────────────────────────────────────────────────────
# Allow the Day 9 frontend (Next.js dev server on :3000 or any origin during
# development) to call the API without browser CORS errors.
# Tighten allowed_origins to ["http://localhost:3000"] for production.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],          # Open for local development
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# ── HTTP Routes ───────────────────────────────────────────────────────────────

@app.get("/", tags=["meta"])
async def root():
    """
    Root endpoint — returns API metadata and quickstart links.

    Useful for a quick sanity check that the server is running:
        curl http://localhost:8000/
    """
    return {
        "service": "AI Driving Assistant API",
        "version": "0.7.0",
        "day": 7,
        "description": (
            "Real-time ADAS pipeline streamed over WebSocket. "
            "Connect to /ws/stream to receive annotated frames + metadata JSON."
        ),
        "endpoints": {
            "websocket_stream": "ws://localhost:8000/ws/stream",
            "swagger_ui":       "http://localhost:8000/docs",
            "redoc":            "http://localhost:8000/redoc",
            "health":           "http://localhost:8000/health",
        },
    }


@app.get("/health", tags=["meta"])
async def health():
    """
    Minimal liveness probe.

    Returns HTTP 200 with ``{"status": "ok"}`` as long as the server process
    is running. Used by Docker HEALTHCHECK directives and load balancers.
    Does NOT check whether the pipeline is operational (that requires an active
    WebSocket connection).
    """
    return {"status": "ok"}


# ── WebSocket Route ───────────────────────────────────────────────────────────

@app.websocket("/ws/stream")
async def websocket_stream(websocket: WebSocket):
    """
    Main WebSocket endpoint — streams the full ADAS pipeline output.

    **Protocol** (one message per processed frame):

    ```json
    {
      "frame_b64": "<base64-encoded JPEG string>",
      "metadata": {
        "frame_number": 42,
        "timestamp": 1234.567,
        "fps_current": 12.4,
        "lane_offset": -0.12,
        "tracked_objects": [
          {
            "track_id": 7,
            "class_name": "car",
            "bbox": [320, 210, 580, 430],
            "confidence": 0.91,
            "estimated_distance_m": 18.3,
            "closing_speed_mps": 2.1,
            "ttc_seconds": 8.7,
            "risk_level": "SAFE",
            "in_ego_lane": true
          }
        ],
        "active_alert": null
      }
    }
    ```

    To render the frame in a browser `<img>` tag:
    ```javascript
    ws.onmessage = (event) => {
        const data = JSON.parse(event.data);
        videoEl.src = 'data:image/jpeg;base64,' + data.frame_b64;
        // update dashboard from data.metadata ...
    };
    ```
    """
    await stream_pipeline(websocket)
